### PR TITLE
Use black code formatting

### PR DESCRIPTION
**Pull request by pipermerriam**
## What was wrong?

Code style..... not always the same.... can be distracting sometimes...

## How was it fixed?

don't think about it and use `black`

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by pipermerriam** [comment]
PR opened to gauge whether we're ready for this here in a smaller library.

**Comment by ralexstokes** [comment]
i would support trying this out for a bit in a more isolated context at first

**Comment by cburgdorf** [comment]
I'm :+1: as well. But maybe we wait until #42 was rebased or even wait some more days if there's currently more open work in flux. I'd assume rebasing changes on top of  a `black` reformatting might not be fun. It's not the end of the world but the black formatting is cheap and can easily be made after the dust has settled.

**Comment by pipermerriam** [comment]
@ralexstokes am I correct interpreting that to mean *"yes, I support trying it out here in the `lahja` codebase where it is smaller and more isolated than it was in `trinity`"*

**Comment by ralexstokes** [comment]
@pipermerriam yep, 👍  :) i realize that was more ambiguous than i intended now that i'm re-reading it...

**Comment by cburgdorf** [comment]
@pipermerriam Unless you have some other open work that would be send in merge conflict hell by this change, I think we can bring this up to date and land it. I'd like to cut a new Lahja release this week and I think black could already be included there.

**Comment by pipermerriam** [comment]
Nothing blocking this other than me rebasing/cleaning.  Let me do that real quick.

**Comment by pipermerriam** [comment]
@cburgdorf do you want to :eyes: this before merge?

**Pull request merged**
